Update sqliv.py
Was Receiving: File "sqliv.py", line 36
    print ""  # move carriage return to newline
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(""  # move carriage return to newline)?